[versions]
agp = "8.4.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"

[libraries]
appcompat = "androidx.appcompat:appcompat:1.3.1"
material = "com.google.android.material:material:1.4.0"
activity = "androidx.activity:activity:1.3.1"
constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.0"
junit = "junit:junit:4.13.2"
ext-junit = "androidx.test.ext:junit:1.1.3"
espresso-core = "androidx.test.espresso:espresso-core:3.4.0"
picasso = "com.squareup.picasso:picasso:2.71828"
retrofit = "com.squareup.retrofit2:retrofit:2.9.0"
converter-gson = "com.squareup.retrofit2:converter-gson:2.11.0"
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

